application: rock-paper-scissors-2468
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index\.html
  secure: always

# This handler routes requests to your APIs to your Endpoints code.
# See https://developers.google.com/appengine/docs/python/endpoints/
- url: /_ah/spi/.*
  script: rps.APPLICATION


libraries:
# You must include the Endpoints library if you wish to serve an API.
- name: endpoints
  version: latest

# pycrypto library used for OAuth2 (req'd for authenticated APIs)
- name: pycrypto
  version: latest